import Link from "next/link";
import { Sparkles } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-200 selection:bg-red-600 selection:text-white">
      {/* Simple Header */}
      <header className=" border-b border-zinc-800/80 bg-zinc-950/80 backdrop-blur-md px-6 py-4 ">
        <div className="flex items-center justify-between max-w-7xl mx-auto">
          <Link href="/" className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-xl bg-linear-to-tr from-red-600 to-rose-500 flex items-center justify-center shadow-lg shadow-red-600/20">
              <Sparkles className="h-4 w-4 text-white" />
            </div>
            <span className="font-bold text-base tracking-tight text-white">
              OmniStudio<span className="text-red-500">.AI</span>
            </span>
          </Link>
          <Link
            href="/login"
            className="text-xs font-medium text-zinc-400 hover:text-white"
          >
            Back to App
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-2">
            Terms of Service
          </h1>
          <p className="text-xs text-zinc-400">Last Updated: August 11, 2026</p>
        </div>

        <section className="space-y-4 text-sm text-zinc-300 leading-relaxed">
          <h2 className="text-lg font-semibold text-white">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using <strong>OmniStudio.AI</strong>{" "}
            (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;), you agree to
            be bound by these Terms of Service. If you do not agree to all of
            these terms, do not use our platform or services.
          </p>

          <h2 className="text-lg font-semibold text-white pt-4">
            2. Description of Service
          </h2>
          <p>
            OmniStudio.AI is an AI-powered studio and workflow platform that
            allows users to create, manage, and optimize digital content. We
            reserve the right to modify, suspend, or discontinue any part of the
            service at any time without notice.
          </p>

          <h2 className="text-lg font-semibold text-white pt-4">
            3. User Accounts & Security
          </h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              You must provide accurate and complete registration information
              when creating an account via social authentication or email.
            </li>
            <li>
              You are responsible for safeguarding your account credentials and
              for all activities that occur under your account.
            </li>
            <li>
              Notify us immediately of any unauthorized use or security
              breaches.
            </li>
          </ul>

          <h2 className="text-lg font-semibold text-white pt-4">
            4. Acceptable Use
          </h2>
          <p>
            You agree not to misuse the service. Prohibited activities include:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Violating any applicable laws or regulations.</li>
            <li>
              Uploading or generating malicious code, harmful data, or illegal
              content.
            </li>
            <li>
              Attempting to reverse-engineer, disrupt, or gain unauthorized
              access to our infrastructure or other users&apos; accounts.
            </li>
          </ul>

          <h2 className="text-lg font-semibold text-white pt-4">
            5. Intellectual Property
          </h2>
          <p>
            All platform software, designs, text, graphics, and logos are the
            property of OmniStudio.AI and are protected by intellectual property
            laws. Content generated by you through your use of the platform
            remains yours, subject to the licenses necessary for us to provide
            the service.
          </p>

          <h2 className="text-lg font-semibold text-white pt-4">
            6. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by law, OmniStudio.AI shall not be
            liable for any indirect, incidental, special, consequential, or
            punitive damages arising out of or related to your use of the
            platform.
          </p>
        </section>
      </main>
    </div>
  );
}
